# Section A: Data Structures & Control Structures

##### 1.Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [2]:
#create a list
lst = [3, 4, 2, 1, 5]
print('list created is: ',lst)

#append()
lst.append(7)
print('list after append: ',lst)

#extend()
lst.extend([8,9])
print('list after append: ',lst)

#insert()
lst.insert(5,6)
print('list after insert: ',lst)

#remove()
lst.remove(8)
print('list after remove: ',lst)

#pop()
lst.pop(-1)
print('list after pop: ',lst)

#index()
print('index of 5 is: ',lst.index(5))

#count()
print('count of 4 is: ',lst.count(4))

#sort()
lst.sort()
print('sorted list: ',lst)

#reverse
lst.reverse()
print('reversedlist: ',lst)

#clear()
lst.clear()
print('after clear: ',lst)

list created is:  [3, 4, 2, 1, 5]
list after append:  [3, 4, 2, 1, 5, 7]
list after append:  [3, 4, 2, 1, 5, 7, 8, 9]
list after insert:  [3, 4, 2, 1, 5, 6, 7, 8, 9]
list after remove:  [3, 4, 2, 1, 5, 6, 7, 9]
list after pop:  [3, 4, 2, 1, 5, 6, 7]
index of 5 is:  4
count of 4 is:  1
sorted list:  [1, 2, 3, 4, 5, 6, 7]
reversedlist:  [7, 6, 5, 4, 3, 2, 1]
after clear:  []


##### 2. Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [3]:
#create a tuple
names = ('Tom', 'Jim', 'Mary')

#trying to change the second name
names[1] = 'Alice'
print(names)

TypeError: 'tuple' object does not support item assignment

##### Explaination: Tuple is immutable, if we want to change items it is better to use list. Here when we try to replace the second name "Jim" with "Alice", Python gives a TypeError because tuples do not allow modification of their elements.

##### 3. Create a set of integers with some duplicate values. Print the set and explain the output.

In [4]:
num = {30, 40, 20, 30, 50,30}

print('set: ',num)

set:  {40, 50, 20, 30}


##### Explaination: The duplicate values 10 and 20 are automatically removed because a set stores only unique elements. Therefore, the set contains only 10, 20, 30, 40, and 50. The order appears as {50, 20, 40, 10, 30} because sets are unordered, so elements may be displayed in a different order each time the program runs.*


##### 4. Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [7]:
#create a dictionary
dict1 = {'name': 'Thomas',
         'Age' : 25,
         'City' : 'Banglore'
        }

#updating the age
dict1['Age'] = 27

#add new key email
dict1['email'] = 'thomas@gmail.com'

#final dictionary
dict1

{'name': 'Thomas', 'Age': 27, 'City': 'Banglore', 'email': 'thomas@gmail.com'}

##### 5. Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [8]:
#enter age
age = int(input('Enter your age: '))

#checking if a person is eligible to vote
if age >= 18:
    print('you are eligible to vote.')
else:
    print('Sorry! you are not eligible to vote')

Enter your age:  25


you are eligible to vote.


##### 6.Given a 'marks' variable, print the grade:
##### - 90 and above: 'A'
##### - 75–89: 'B'
##### - 50–74: 'C'
##### - Below 50: 'Fail'

In [13]:
#marks of a student
marks = 30

#check the grade
if marks >= 90:
    print('Grade: A')
elif marks >= 75:
    print('Grade: B')
elif marks >= 50:
    print('Grade: C')
else:
    print('Fail')

Fail


##### 7.Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [15]:
num = 3

if num > 0:
    print('Number is positive')

    if num % 2 == 0:
        print('Number is even')
    else:
        print('Number is odd')

elif num == 0:
    print('Number is zero')

else:
    print('Number is negative')

Number is positive
Number is odd


# Section B: Numpy

##### 8.Create:
##### - A scalar using np.array(5)
##### - A 1D array with values 1 to 5
##### - A 2D array (2x3) with values from 10 to 60 in steps of 10

In [4]:
import numpy as np
#scalar
scalar = np.array(5)
print(scalar)

#A 1D array with values 1 to 5
arr = np.array([1, 2, 3, 4, 5])
print('\n1D array : ')
print(arr)

# A 2D array (2x3) with values from 10 to 60 in steps of 10
arr1 = np.array([[10, 20, 30], [40, 50, 60]])
print('\n2D array: ')
print(arr1)

5

1D array : 
[1 2 3 4 5]

2D array: 
[[10 20 30]
 [40 50 60]]


##### 9. Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [6]:
array = np.random.randint(0, 101, size = (4, 4))
print('Array of random integers: ')
print(array)

Array of random integers: 
[[79 63  0 44]
 [31 73 31  6]
 [81  8 61 70]
 [52 98 56  9]]


##### 10. Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [8]:
import pandas as pd

#create a 2D numpy array
arr2 = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90]])

#convert it into DataFrame
df = pd.DataFrame(arr2, columns = ['A', 'B', 'C'])
print(df)

    A   B   C
0  10  20  30
1  40  50  60
2  70  80  90


# Section C: Exploring Pandas

##### 11. Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
##### - Use .info(), .describe()
##### - Select 'Name' and 'City' columns
##### - Drop 'City' column
##### - Fill any missing values in 'Salary' column with the mean
##### - Remove any duplicate rows

In [1]:
import pandas as pd

Data = {
        'Name' : ['Anu', 'Arjun', 'Asha', 'Pooja', 'Kashi',
                  'Chandu', 'Kirthi', 'Samay', 'Niraj', 'Prajna'],
        'Age' : [20, 25, 22, 30, 28, 24, 22, 31, 26, 27],
        'City' : ['Banglore', 'Pune', 'Mumbai', 'Chennai', 'Hyderbad',
                  'Kochi', 'Banglore', 'Chennai', 'Mumbai', 'Delhi'],
        'Salary' : [20000,30000,25000,40000,33000,19000,22000,36000,27000,36000]
}

df = pd.DataFrame(Data)

#1. Display info
print("DataFrame info: ")
df.info()

#2.Display description
print("\nDataFrame Description: ")
df.describe()

#3.select name and city column
print("\n Name and City columns: ")
df.loc[:,['Name' , 'City']]

#4.Drop 'City' column
print("\n Drop city: ")
df.drop('City')

#5.

DataFrame info: 
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    10 non-null     object
 1   Age     10 non-null     int64 
 2   City    10 non-null     object
 3   Salary  10 non-null     int64 
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes
DataFrame Description: 


,Age,Salary
count,10.000000,10.000000
mean,25.500000,28800.000000
std,3.597839,7345.444544
min,20.000000,19000.000000
25%,22.500000,22750.000000
50%,25.500000,28500.000000
75%,27.750000,35250.000000
max,31.000000,40000.000000
